### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by AbiChi** [team2181/FRC2016#11]
Jason asked us to code the camera, but the ones here didn't know unfortunately. Maybe the CameraServer class? It's a USB so maybe just using StartAutomaticCapture that sends images to the dashboard and if so not sure where that would go on the code. Would that be another subsystem? Would we only need to set it to capture or do we have to set brightness, fps, etcetera? Is it an axis camera? Will it need configuring?

**Comment by Brekmister** [comment]
Webtekz is doing this personally. He said there would be some reconition stuff going on in the camera. That kind of thing is even beyond me.

**Comment by webtekz** [comment]
Maybe. Maybe. I'm going to see if maybe it'll happen, at minimum it'll be on SmartDashboard, at maximum it's going to have full VISION integration and the robot will be able to home in on the target. Automatically.

**Comment by webtekz** [comment]
Resolved in d5354ba8992532b8285d5ce01bf29407ab7645e0
