### ISSUE TITLE
Autonomous Period

### ISSUE THREAD

**Issue by Brekmister** [team2181/FRC2016#12]
Here it is everyone, this is what we have been waiting for. Its our time to shine. We are going to use `epic wizardy` that nobody else on the team understands to turn a giant paperweight into something that will make the Judges say "Wow! That is some Robot!"

In order to do that, We need to make sure that you as a programmer has the proper tools and knowledge to make the robot work on autonomous period.

**Comment by Brekmister** [comment]
Here is how Autonomous Period is going to work (WIP):

There are 3 possible starting positions and 6 places the obstacles will be and 3 types of obstacles we are coding for. On the `SmartDashboard` we need input for each obstacle and position and have code for every possibility while using Distance, Time and the Gyrometer to navigate

If possible we should also include code to pick up a ball A.K.A Boulder and shoot it into the goal

If the user does not select all 3 required inputs, then the robot will do nothing for autonomous period

**Comment by webtekz** [comment]
Understand that autonomous is extremely finicky. No matter what, we are going to have to deal with a fairly large margin for error, and you are going to be spending time just tweaking timings and power settings. Try to keep your code as clean as possible, and when we start creating the Autonomous CommandGroups, we want as much as possible editable from these CommandGroups. I'll go over the specifics in time.

The selection process that Brekmister detailed above will be accomplished by placing two radio-button style selectors in SmartDashboard: one for the starting positions, and the other for the types of obstacles. theabsentmindedprofessor and I already went over that, and I'll see about getting that assigned to her.

Our autonomous programs will be running, as I mentioned above, from `CommandGroup`, a `Command`-extending class that is made for running multiple other commands in a sequence. We will be creating autonomous-specific commands, as well as these `CommandGroup` objects to sequence these commands. The appropriate `CommandGroup` will be run when the autonomous program is selected, and the robot is enabled.

As far as the camera is concerned, I will be personally working on that end. I am extremely unsure as to how far we will go with the camera, but just know that working with it, in general, is absolutely insane. :P

**Comment by Brekmister** [comment]
Webtekz, for our sake, are you going to use a library other than WPIlib? If so, what?

**Comment by webtekz** [comment]
https://wpilib.screenstepslive.com/s/4485/m/50711/l/481750-using-grip-for-the-2016-game

GRIP. External application used for image processing and filtering, and the brand-new official way to do VISION processing. 

Also, feel free to use my real name. It shows up in my profile.

**Comment by Brekmister** [comment]
I just felt like it, Steven. ;)

**Comment by webtekz** [comment]
lol, fair enough, then.

**Comment by Brekmister** [comment]
And also If you do have your own laptop (With administrator privileges),
Please Please bring it and I can help you get it set up if you haven't
already. If you don't, Then let me know ASAP and ill get you set up with
one.

**Comment by Brekmister** [comment]
Here's what FRC suggests how we use commands in our autonomous code in `Robot.cpp`:

`HelloCommand.h` = Header File of the command you want to use

After including the header file, we have to make a new command, this time we call it `Foo` Because, you know, `Foo`. And make that equal to a new object in `HelloCommand` Command Class

`#Include "Commands/HelloCommand.h"`
`Command* Foo;`
`Foo = new HelloCommand(32);` Placing that in `Robot::RobotInit`. 32 is the parameter given to the command.
And start the command in `Robot::AutonomousInit`:
`if (Foo != null) Foo.start();`

If you want to run the command again with different parameters like say after the Foo is done, you want it to run with a given parameter of 24. You will either have to:
1. Create a Foo2 and make it equal to `new HelloCommand(24)`
   or
2. After `if (Foo != null) Foo.Start();` make Foo equal to `new HelloCommand(24)` then starting it again

**Comment by AbiChi** [comment]
I was thinking we could have five autonomous buttons,
Button1 would just make the robot go forward to pass the defenses we can just drive over(Moat, Ramparts, Rock wall, and Rough Terrain)
Button2 would be for the low bar so it drives forward but also lowers the dart
Button3 would be for the tippy bars(AKA Chival de Frise) so it lowers the dart to push down the boards that are up and then drives over
Button4 for lifting the portcullis
Button5 would be to just drive a little bit forward to reach defenses we can't breach maybe

**Comment by maxar6** [comment]
As far as autonomous goes it is done other then minor tweaks at competition for the timings.

**Comment by maxar6** [comment]
You guys ready to close this thread? Auto is tested and working.

**Comment by Brekmister** [comment]
Close it.
