### ISSUE TITLE
Testing Distance Over Time

### ISSUE THREAD

**Issue by Brekmister** [team2181/FRC2016#13]
In order to get Time/Distance, we need to measure how far the robot goes in a certain time period.

How we get the measurement:
`Robot.cpp` there is a function named `Robot::Test`, Inside that function, someone has to code the procedure that runs a motor for a set power and time.

It should go along the lines of this:

`setMotor(.5), 
Wait(1),
setMotor(0),
Wait(5)
`
This is not correct syntax. Part of this is you finding the correct way of coding this in `Robot.cpp`.

If you can get this done, then everything else will be a cinch except for debugging and camera recognition.

Comment below if you have any issues, questions, concerns, or you need better explanation regarding this.

**Comment by Brekmister** [comment]
Upload to a new branch once your finished and I will look over it. DO NOT FORK!!!!!!

**Comment by AbiChi** [comment]
Put some code in my branch, we haven't tested it yet though

**Comment by webtekz** [comment]
Animal-nerd above had the right idea, but it ends up being slightly more complex than that. I fixed it myself, mainly due to the fact that I have some personal issues that I am dealing with and I won't be able to come to a few meetings, so time is of the essence. I duly apologize.

Resolved by 78f9b0cbcb490ea9414687eec37a30a962bdfce0

**Comment by Brekmister** [comment]
Sure, I tried helping her until I actually was not mentally able to. Since
I was home sick

**Comment by webtekz** [comment]
I'm sorry to hear that. And as far as that problem I mentioned, it really is going to be an issue, I'll talk to you guys about this in private soon enough. We really do have a problem, actually.
