### ISSUE TITLE
TOP PRIORITY - Loader Arm Sensor (updated)

### ISSUE THREAD

**Issue by webtekz** [team2181/FRC2016#4]
_**If you want to work on this task, and I am not there, please respond to this issue and I will assign it to you. Use any help you need, and feel free to work with anyone else, but by being assigned an issue, you are taking responsibility for it. It's not really a huge deal if you mess up, but I would appreciate some effort to try your best.**_

---

The arm sensor has been declared as `loaderSensor` in the `Launcher` subsystem. It is a digital input. We need the loader arm to rotate 360 degrees once at the press of a button, using the sensor as a reference starting point. The way I would recommend doing this is by creating a new command and setting it to run once (`IsFinished` returns `true`) when a joystick button is pressed. To avoid the command being looped over and over as long as the button as pressed, use the `WhenPressed` function rather than the `WhileHeld` function. **REMEMBER: Creation of new objects (commands, subsystems, I/O) as well as configuration of joysticks should be done through RobotBuilder.**

Tell this command to run a new function within the `Launcher` subsystem that runs the motor for a short amount of time (use `Wait(time)` to delay a program) and then listens for a `true` return from `loaderSensor->Get()`, after which we stop the motor

**Comment by JRTalusan** [comment]
@webtekz I would like to take on this issue.

**Comment by webtekz** [comment]
Done. Ask if you have any questions.

**Comment by webtekz** [comment]
And, apologies for my lack of communication so far. I have tried to send an email, among other things, it's honestly been quite difficult. I cannot meet you in person, due to my schedule with PSEO and all it is physically impossible for me to do so.

**Comment by Brekmister** [comment]
Josh How is it coming? Can you send me what you have VIA Email?
