### ISSUE TITLE
Ultrasonic Sensor Aiming System

### ISSUE THREAD

**Issue by Brekmister** [team2181/FRC2016#6]
The Ultrasonic sensor installed on the robot is going to be used to gauge the distance between the robot and the castle. Using the value given from the Ultrasonic sensor and Jasons Formula, We as programmers are requested to implement a system that is used to tell the driver EXACTLY where to aim through `SmartDashboard`.

Jasons Formula:
`P=-0.0102*(U*42.0919)^2+3.0804*(U*42.0919)+210.79. Where P = potentiometer value and U = Ultrasonic Value.`

For right now have the accepted range to be +-15 of P.

**Comment by Brekmister** [comment]
Got it done and Uploaded to AutoAim Branch. Closing Issue.

**Comment by webtekz** [comment]
Appreciated. I'll look over it and work on getting it merged in tomorrow.
