### ISSUE TITLE
Get Gyro to work <TOP PRIORITY>

### ISSUE THREAD

**Issue by Brekmister** [team2181/FRC2016#8]
The Gyro on the RoboRio needs to be programmed so we can start developing the Autonomous System for the robot.

The only issue is that, Our Gyro is not hooked up to any of the Analog Ports, So, we can not use Robot Builder to put the Gyro into the Code since Robot Builder uses `AnalogGyro` Class which handles Gyros hooked up to the Analog Ports not the `Gyro` Class that Handles all of the Gyros that was supplied by FRC.

The name for the Gyro in WPILib is `ADXRS450`

**Comment by webtekz** [comment]
Alright, looked at the implementation, seems easy enough. We do need to figure out how calibration works, though, don't know what we need to do exactly. 

Either way, doesn't look too bad.

**Comment by Brekmister** [comment]
Yeah I am currently working on it. I just found out how to add new sensors in a robotbuilder export without robotbuilder. Then its just things like `GetAngle()`, `Calibrate()` and `Reset()`

**Comment by Brekmister** [comment]
C++ has wierd way of doing pointers however

**Comment by webtekz** [comment]
Alright, sounds good. 

And it does. C++ is weird in general.

**Comment by webtekz** [comment]
Btw, I imagine you are talking about the unique_ptr<Object> stuff?

**Comment by Brekmister** [comment]
That and also shared_ptr

**Comment by webtekz** [comment]
Yeah, that's C++11 insanity, you can also just use normal C syntax

**Comment by Brekmister** [comment]
Oh cool. so things like double\* foo

**Comment by webtekz** [comment]
Yeah, things like double *foo = &bar, so and so. C++ is mostly C-compatible.

**Comment by Brekmister** [comment]
Nice to know

**Comment by webtekz** [comment]
Yep. Only reason I bother with the unique_ptr stuff anyway is because RobotBuilder uses them. If I had to actually make a pointer I'd just use C syntax.

**Comment by Brekmister** [comment]
Kk

**Comment by Brekmister** [comment]
Got gyro done. Will push to a new branch.

**Comment by Brekmister** [comment]
Pushed to new branch. Issue Closed
